config/routes.rb
Channelgameroom::Application.routes.draw do

  root :to => "welcome#index"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/auth/failure" => "sessions#auth_failure", :as => :auth_failure

  resources :games
  match "/games/:id/videos" => "games#videos"

  match "/likes/vote" => "likes#vote", :as => :vote

  resources :systems
  match "/systems/:system/games" => "systems#show", :as => :system_games
  match "/systems/:system/games/:filter" => "systems#show", :as => :system_games_filtered

end

app/models/game.rb
class Game < ActiveRecord::Base

  # Associations
  belongs_to :system
  has_many :videolinks, :dependent => :destroy
  accepts_nested_attributes_for :videolinks, :reject_if => lambda { |a| a[:url].blank? }

  # Attributes
  attr_accessible :system_id, :title, :description, :moby_url, :videolinks_attributes
  
  # Callbacks
  before_save :update_permalink
  
  # Scopes
  default_scope :order => "title"
  
  # Validations
  validates_presence_of :system_id, :message => "game system required"
  validates_presence_of :title
  
  def to_param
    "#{id}-#{permalink}"
  end
    
  def update_permalink
    self.permalink = "#{self.title.to_slug}-#{self.system.slug}"
  end
  
  def self.search(query)
    conditions = <<-EOS
      search_vector @@ to_tsquery('english', ?)
    EOS
    
    where(conditions, query)
  end
  
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json

  def index    
    if params[:search].present?
      @games = Game.search(params[:search]).page(params[:page]).per(25)
    else
      @games = Game.page(params[:page]).per(25)
    end
  end
  
  def show
    @video_id = (params[:video_id].to_i - 1) || 0
    @video_id = 0 if @video_id < 0
      
    @game = Game.find(params[:id])
    @link = (@game.videolinks[@video_id].url_html || "") unless @game.videolinks[@video_id].nil?
    
    respond_with( @game )
  end
  
  def new
    @game = Game.new
    3.times { @game.videolinks.build }
  end
  
  def create
    @game = Game.new(params[:game])
    if @game.save
      flash[:notice] = "Successfully created game."
      redirect_to @game
    else
      render :action => 'new'
    end
  end
  
  def edit
    @game = Game.find(params[:id])
    3.times { @game.videolinks.build }
  end
  
  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      flash[:notice] = "Successfully updated game."
      redirect_to @game
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:notice] = "Successfully destroyed game."
    redirect_to games_url
  end
  
  
  def videos
    results = {}
    number_of_videolinks = 0
    
    @game = Game.find(params[:id])
    
    if @game.present?
      like = Like.where(:user_id => current_user.id, :likeable_id => @game.id, :likeable_type => "Game").first if current_user
      results["Status"] = "OK"
      results["game_id"] = @game.id
      results["liked"] = (like.amount if like.present?) || 0
      results["videolinks"] = {}
      
      @game.videolinks.each_with_index do |vl, i|
        videolink = {}
        like = Like.where(:user_id => current_user.id, :likeable_id => vl.id, :likeable_type => "Videolink").first if current_user
        videolink["id"] = vl.id
        videolink["url_html"] = vl.url_html
        videolink["liked"] = (like.amount if like.present?) || 0
        results["videolinks"][i] = videolink
        number_of_videolinks += 1
      end
      results["number_of_videolinks"] = number_of_videolinks
    else
      results["Status"] = "Error"
      results["Message"] = "Can't find that game"
    end
    
    respond_with( @videos = results.to_json )
  end
  
  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/show/_head.html.erb
<% content_for(:sheet_header) do %>
	<ul>
		<li><%= link_to "Edit", edit_game_path(@game) %></li>
	</ul>
<% end %>

<h1>
	<%= @game.title %>
	<span class="game_system"><%= @game.system.name %></span>
</h1>

app/views/games/show/_info.html.erb
<div class="row">
	<div class="twelvecol last">
		
		
		<% if @game.moby_url.present? %>
			<%= link_to "View on Moby Games", "http://mobygames.com#{@game.moby_url}", :target => "_blank" %>
		<% end %>

	</div>
	
</div>

app/views/games/show/_video.html.erb
<div class="row">
	<div class="twelvecol">

 		<center><div id="video"><%= raw @link %></div></center>

		<div class="video_nav">
			<ul>
				<% if @link.present? %>
					<li><%= link_to "", "#", :id => "prevVideo", :title => "Previous video...", :class => "prev" %></li>
					<li><%= link_to "", "#", :id => "nextVideo", :title => "Next video...", :class => "next" %></li>
					<% if current_user %>

						<li><%= link_to "", "#", :id => "likeGame", :title => "Like game", :class => "likegame" %></li>
						<li><%= link_to "", "#", :id => "hateGame", :title => "Hate game", :class => "hategame" %></li>

						<li><%= link_to "", "#", :id => "likeVideo", :title => "Like video", :class => "likevideo" %></li>
						<li><%= link_to "", "#", :id => "hateVideo", :title => "Hate video", :class => "hatevideo" %></li>
					<% end %>
				<% end %>
			</ul>
		</div>

		<div class="video_info" id="video_info">Video</div>

	</div>


</div>