config/routes.rb
Channelgameroom::Application.routes.draw do

  root :to => "welcome#index"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/auth/failure" => "sessions#auth_failure", :as => :auth_failure

  resources :games
  match "/games/:id/videos" => "games#videos"

  match "/likes/vote" => "likes#vote", :as => :vote

  resources :systems
  match "/systems/:system/games" => "systems#show", :as => :system_games
  match "/systems/:system/games/:filter" => "systems#show", :as => :system_games_filtered

end

app/models/game.rb
class Game < ActiveRecord::Base

  # Associations
  belongs_to :system
  has_many :videolinks, :dependent => :destroy
  accepts_nested_attributes_for :videolinks, :reject_if => lambda { |a| a[:url].blank? }

  # Attributes
  attr_accessible :system_id, :title, :description, :moby_url, :videolinks_attributes
  
  # Callbacks
  before_save :update_permalink
  
  # Scopes
  default_scope :order => "title"
  
  # Validations
  validates_presence_of :system_id, :message => "game system required"
  validates_presence_of :title
  
  def to_param
    "#{id}-#{permalink}"
  end
    
  def update_permalink
    self.permalink = "#{self.title.to_slug}-#{self.system.slug}"
  end
  
  def self.search(query)
    conditions = <<-EOS
      search_vector @@ to_tsquery('english', ?)
    EOS
    
    where(conditions, query)
  end
  
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json

  def index    
    if params[:search].present?
      @games = Game.search(params[:search]).page(params[:page]).per(25)
    else
      @games = Game.page(params[:page]).per(25)
    end
  end
  
  def show
    @video_id = (params[:video_id].to_i - 1) || 0
    @video_id = 0 if @video_id < 0
      
    @game = Game.find(params[:id])
    @link = (@game.videolinks[@video_id].url_html || "") unless @game.videolinks[@video_id].nil?
    
    respond_with( @game )
  end
  
  def new
    @game = Game.new
    3.times { @game.videolinks.build }
  end
  
  def create
    @game = Game.new(params[:game])
    if @game.save
      flash[:notice] = "Successfully created game."
      redirect_to @game
    else
      render :action => 'new'
    end
  end
  
  def edit
    @game = Game.find(params[:id])
    3.times { @game.videolinks.build }
  end
  
  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      flash[:notice] = "Successfully updated game."
      redirect_to @game
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:notice] = "Successfully destroyed game."
    redirect_to games_url
  end
  
  
  def videos
    results = {}
    number_of_videolinks = 0
    
    @game = Game.find(params[:id])
    
    if @game.present?
      like = Like.where(:user_id => current_user.id, :likeable_id => @game.id, :likeable_type => "Game").first if current_user
      results["Status"] = "OK"
      results["game_id"] = @game.id
      results["liked"] = (like.amount if like.present?) || 0
      results["videolinks"] = {}
      
      @game.videolinks.each_with_index do |vl, i|
        videolink = {}
        like = Like.where(:user_id => current_user.id, :likeable_id => vl.id, :likeable_type => "Videolink").first if current_user
        videolink["id"] = vl.id
        videolink["url_html"] = vl.url_html
        videolink["liked"] = (like.amount if like.present?) || 0
        results["videolinks"][i] = videolink
        number_of_videolinks += 1
      end
      results["number_of_videolinks"] = number_of_videolinks
    else
      results["Status"] = "Error"
      results["Message"] = "Can't find that game"
    end
    
    respond_with( @videos = results.to_json )
  end
  
  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game do |f| %>

	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.association :system %>
	
	
	<%= f.simple_fields_for :videolinks do |link| %>
		<%= link.input :url, :label => "Youtube Link " %>
	<% end %>
	
	
	<%= f.button :submit %> or <%= link_to "Cancel", @game %>
	
<% end %>

app/views/games/edit.html.erb
<h2>Edit <%= @game.title %></h2>
<%= render "form" %>

app/views/games/index.html.erb
<% content_for(:sheet_header) do %>
	<ul>
		<li><%= link_to "New Game", new_game_path %></li>
	</ul>
<% end %>

<div class="game_search">
	<% form_tag games_path, :method => 'get' do %>
		<p>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name => nil %>
		</p>
	<% end %>
	<%= paginate @games %>
</div>

<div class="game_list">
	<div class="container">
		<div class="row">			
			<% @games.each do |game| %>
				<div class="sixcol">
					<%= link_to "#{game.title}", game %><br />
					<%= game.description %>
				</div>
				<div class="sixcol last game_list_system">
					<%= game.system.name %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/games/new.html.erb
<div class="row">
	<div class="eightcol">
		<h2>New Game</h2>
		<%= render "form" %>
	</div>
	<div class="fourcol last">
		<h2>Rules</h2>
		<p>
			Please make sure you aren't entering a duplicate game by doing a search first.
		</p>
		<p>
			Keep the title clean. <br />
			For example, use "Mega Man 3" instead of "Megaman Three for NES".<br />
			You don't have to enter the system in the title.
			
		</p>
	</div>
</div>

app/views/games/show.html.erb
<% content_for(:head) do %>
	<script type="text/javascript" charset="utf-8">var game_id = <%= @game.id %>;var video_id = <%= params[:video_id].to_i - 1 || 0 %>;</script>
<% end %>

<div class="game">
	<%= render "games/show/head" %>
	<%= render "games/show/video" %><br />
	<%= render "games/show/info" %><br />
</div>

<% content_for(:js) do %>
	<%= javascript_include_tag 'video' %>	
<% end %>