config/routes.rb
Channelgameroom::Application.routes.draw do

  root :to => "welcome#index"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/auth/failure" => "sessions#auth_failure", :as => :auth_failure

  resources :games
  match "/games/:id/videos" => "games#videos"

  match "/likes/vote" => "likes#vote", :as => :vote

  resources :systems
  match "/systems/:system/games" => "systems#show", :as => :system_games
  match "/systems/:system/games/:filter" => "systems#show", :as => :system_games_filtered

end

app/models/system.rb
class System < ActiveRecord::Base
  has_many :games


  default_scope :order => "name"

end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  
  def index
    @systems = System.all
  end
  
  def show
    @system = System.find_by_slug(params[:system])
    
    if params[:filter].present?
      if params[:filter] == "0-9" then
        @games = @system.games.where("title LIKE '0%' OR title LIKE '1%' OR title LIKE '2%' OR title LIKE '3%' OR title LIKE '4%' OR title LIKE '5%' OR title LIKE '6%' OR title LIKE '7%' OR title LIKE '8%' OR title LIKE '9%'")
#        @games = @system.games.where("title LIKE ?", (0-9))
      else
        @games = @system.games.where("title LIKE ?", params[:filter].upcase + '%')
      end
    else
      @games = @system.games if @system.present?
    end
  end
  
end

app/helpers/systems_helper.rb
module SystemsHelper
  
  def a_to_z_links
    str = '<li>' + link_to("All", "/systems/#{@system.slug}/games") + '</li>'
    str += '<li>' + link_to("#", "/systems/#{@system.slug}/games/0-9") + '</li>'
    ("A".."Z").map { |l| str += '<li>' + link_to(l, "/systems/#{@system.slug}/games/#{l.downcase}") + '</li>' }
    raw str
  end
  
  
end

app/views/systems/index.html.erb
<% @systems.each do |system| %>
	<div class="system">
		<span class="name"><%= link_to system.name, system_games_path(system.slug) %></span>
	</div>	
<% end %>


<br />

app/views/systems/show.html.erb
<% if @games.present? %>
<div class="row">
	<div class="eightcol">

		<div class="game_list">
			<h1><%= "#{@system.name} Games" if @system.present? %></h1>
			
			<div class="game_quick_nav">
				<ul>
					<%= a_to_z_links %>
				</ul>
			</div>
			
			<table>
					<tr>
						<th>Game</th>
						<th>Videos</th>
					</tr>
				<% @games.each do |game| %>
					<tr>
						<td><%= link_to game.title, game %></td>
						<td><%= game.videolinks.count %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
	<div class="fourcol last">
	</div>
</div>
<% end %>