config/routes.rb
Channelgameroom::Application.routes.draw do

  root :to => "welcome#index"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/auth/failure" => "sessions#auth_failure", :as => :auth_failure

  resources :games
  match "/games/:id/videos" => "games#videos"

  match "/likes/vote" => "likes#vote", :as => :vote

  resources :systems
  match "/systems/:system/games" => "systems#show", :as => :system_games
  match "/systems/:system/games/:filter" => "systems#show", :as => :system_games_filtered

end

app/helpers/layout_helper.rb
module LayoutHelper
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = h(show_title)
  end
  
end

app/views/layouts/_disqus.html.erb
<script type="text/javascript" src="http://channelgameroom.disqus.com/combination_widget.js?num_items=5&hide_mods=0&color=blue&default_tab=people&excerpt_length=200"></script><a href="http://disqus.com/">Powered by Disqus</a>
<div id="disqus_thread"></div>
<script type="text/javascript">
	var disqus_developer = 1; // developer mode is on
  var disqus_shortname = 'channelgameroom'; // required: replace example with your forum shortname
  var disqus_identifier = '<%= url_id %>';
  var disqus_url = '<%= url_id %>';

	/* * * DON'T EDIT BELOW THIS LINE * * */
	(function() {
	    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
	    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
	    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/layouts/_top_nav.html.erb
<div class="top_nav">
	<div class="sevencol">
		<ul>
			<li><%= link_to "Home", root_url %></li>
			<li><%= link_to "Games", games_path %></li>
			<li><%= link_to "Systems", systems_path %></li>
			<li><%= link_to "About", root_url %></li>
			<li><%= link_to "Contact", root_url %></li>
		</ul>
	</div>
	<div class="fivecol sign_in last">
		<ul>
		<% if current_user %>
			<li><%= current_user.name %>&nbsp;&nbsp;&nbsp;</li>
			<li><%= link_to "Sign Out", signout_path %></li>
		<% else %>
			<li>Sign in with&nbsp;&nbsp;&nbsp;</li>
			<li><%= link_to "FaceBook", "/auth/facebook" %></li>
			<li><%= link_to "Twitter", "/auth/twitter" %></li>
		<% end %>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= stylesheet_link_tag '1140', :media => 'screen' %>

		<!--[if lte IE 9]>
		<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
			<%= stylesheet_link_tag 'ie', :media => 'screen' %>
		<![endif]-->

		<%= stylesheet_link_tag 'typeimg', :media => 'screen' %>
		<%= stylesheet_link_tag 'smallerscreen', :media => 'only screen and (max-width: 1023px)' %>
		<%= stylesheet_link_tag 'mobile', :media => 'handheld, only screen and (max-width: 767px)' %>
		<%= stylesheet_link_tag 'simple_form', :media => 'screen' %>
		<%= stylesheet_link_tag 'layout', :media => 'screen' %>
		
		<link  href="//fonts.googleapis.com/css?family=Molengo:regular" rel="stylesheet" type="text/css" >
		<link  href="//fonts.googleapis.com/css?family=Orbitron:400,500,700,900" rel="stylesheet" type="text/css" >		

		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>Channel Game Room</title>		
		
		<%= csrf_meta_tag %>
		<%= yield(:head) %>
	</head>
	<body>

		<div class="container logo">
			<div class="row">
				<div class="twelvecol last">
					<h1>Channel Game Room</h1>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<%= render "layouts/search" %>
				<%= render "layouts/top_nav" %>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="twelvecol last">
				
					<div class="sheet">
						<div class="header">
							<%= yield(:sheet_header) %>
						<div>
							
						<% flash.each do |name, msg| %>
				    	<%= content_tag :div, msg, :id => "#{name}" %>
				    <% end %>

							
						<%= yield %>
						
					</div>
					
				</div>
			</div>
		</div>
		
	


  	<%= javascript_include_tag ['jquery-1.5.min', 'rails', 'application'] %>
		<%= yield(:js) %>
	</body>
</html>